# StopBrowsing Configuration File
# Website blocker for productivity

# Global settings
enabled: true                        # Enable/disable website blocking
profile: default                     # Website profile to use (default, work, minimal)

# Auto-blocking settings
auto_block:
  on_login: true                      # Automatically block when you log in
  
# Statistics tracking
statistics:
  start_date: ""                      # Format: "2025-06-28" - Set when you start tracking
  track_success: true                 # Enable/disable success day tracking

# DNS-over-HTTPS blocking (prevents browser bypass)
doh_blocking:
  enabled: true                       # Master switch - Block DoH requests for blocked websites only
  
  # Individual blocking layer controls (advanced users)
  block_hosts_file: true              # Layer 1: /etc/hosts file modification 
  block_dot: true                     # Layer 2: DNS over TLS (port 853)
  block_doh: true                     # Layer 3: DNS over HTTPS string matching
  block_tab_closing: true             # Layer 4: Close streaming tabs (replaces connection termination)

# Tab closing configuration (Layer 4)
tab_closing:
  websites:                           # Browser window titles to close
    - "Twitch"                        # Matches "*Twitch*" in window title
    - "TikTok"                        # Matches "*TikTok*" in window title  
    - "YouTube"                       # Matches "*YouTube*" in window title
    - "youtu.be"                      # Matches "*youtu.be*" in window title
    - "Netflix"                       # Matches "*Netflix*" in window title
    - "Instagram"                     # Matches "*Instagram*" in window title
    - "Facebook"                      # Matches "*Facebook*" in window title

# ============================================================================
# Website Lists: Use 'stopbrowsing -e' to edit blocked websites
# Statistics: View with 'stopbrowsing --status' 
# Reset Everything: Use 'stopbrowsing --reset' to start fresh
# ============================================================================
